<!-- Auto-generated by psd2code (vue target) -->
<!-- Do not edit by hand; re-run psd_to_code.py --target vue to regenerate. -->
<template>
  <svg class="svg-filters" aria-hidden="true">
    <defs>
      <filter id="spin-text-knockout" color-interpolation-filters="sRGB">
        <feColorMatrix
          type="matrix"
          values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0.299 0.587 0.114 0 0"
        />
        <feComponentTransfer>
          <feFuncA type="linear" slope="15" intercept="0" />
        </feComponentTransfer>
      </filter>
    </defs>
  </svg>
  <div class="scale-viewport" :style="viewportStyle">
  <div id="canvas" :style="canvasStyle">
    <div class="bg layer"></div>
    <div class="shouye layer-group">
      <div class="shouye-bg layer"></div>
      <div class="shouye-icon layer"></div>
      <div class="home-cat-hits">
        <button
          type="button"
          class="home-cat-hit home-cat-hit--checkin"
          :aria-label="t('nav.checkinEvent')"
          @click="scrollToSection('checkin')"
        ></button>
        <button
          type="button"
          class="home-cat-hit home-cat-hit--topup"
          :aria-label="t('nav.topupRewards')"
          @click="scrollToSection('topup')"
        ></button>
        <button
          type="button"
          class="home-cat-hit home-cat-hit--wheel"
          :aria-label="t('nav.luckyWheel')"
          @click="scrollToSection('wheel')"
        ></button>
      </div>
    </div>
    <div class="bg-2 layer-group v-col">
      <div class="mousi-row v-row">
        <div class="mousi layer"></div>
        <div class="ludewei layer"></div>
      </div>
      <div class="rect layer"></div>
      <div class="img-6 layer"></div>
      <div class="img-7 layer"></div>
      <div class="bg-2-2-stack v-stack">
        <div class="bg-2-2 layer"></div>
        <div class="linshiyan layer"></div>
      </div>
      <div class="img-2 layer"></div>
      <div class="img-stack v-stack">
        <div class="img layer"></div>
        <div class="img-3-2 layer"></div>
        <div class="img-5 layer"></div>
        <div class="img-4 layer"></div>
      </div>
    </div>
    <div class="slogan-checkin layer-group v-col">
      <div class="title layer-group">
        <div class="btn-checkin layer"></div>
        <div class="title-text layer">
          <span>{{ t('event.duration', { range: eventDurationText }) }}</span>
        </div>
      </div>
      <div class="checkin-frame layer-group v-col">
        <div class="rect-2-stack v-stack">
          <div class="rect-2 layer"></div>
          <div class="rect-2-2 layer"></div>
          <div class="rect-3-2 layer"></div>
          <div class="role layer-group">
            <div class="rect-3 layer"></div>
            <div class="role-2 layer" :style="carouselImageStyle"></div>
          </div>
          <div class="arrow layer-group is-clickable" @click="showCarouselPrev">
            <div class="rect-4 layer"></div>
            <div class="rounded layer"></div>
          </div>
          <div class="arrow-2 layer-group is-clickable" @click="showCarouselNext">
            <div class="rect-5 layer"></div>
            <div class="rounded-2 layer"></div>
          </div>
          <div class="checkin-frame-text layer">
            <span>{{ t('checkin.currentTime', { time: currentUtc5Text }) }}</span>
          </div>
        </div>
        <div class="reward layer is-clickable" @click="handleRewardHistoryClick">
          <span>{{ t('checkin.rewardHistory') }}</span>
        </div>
      </div>
      <div class="reward-2 layer-group v-col">
        <div class="reward-bg-3-stack v-stack">
          <div class="reward-bg-3 layer-group">
            <div class="rect-6 layer"></div>
            <div class="rect-2-3 layer"></div>
            <div class="rect-3-3 layer"></div>
          </div>
          <div class="btn-checkin-2 layer">
            <span>{{ t('checkin.dailyCheckinRewards') }}</span>
          </div>
        </div>
        <div class="reward-bg-2-stack v-stack">
          <div class="reward-bg-2 layer-group">
            <div class="rect-7 layer"></div>
          </div>
          <div class="reward-bg layer-group v-col">
            <div class="yingwen-row v-row">
              <div class="yingwen-stack v-stack" :class="getDayClass(1)" @click="handleDayClick(1)">
                <div class="yingwen layer"></div>
                <div class="day1 layer-group">
                  <div class="day1-text layer">
                    <span>day 1</span>
                  </div>
                  <div class="gem layer">
                    <span>Diamond x100</span>
                  </div>
                </div>
              </div>
              <div class="day2 layer-group" :class="getDayClass(2)" @click="handleDayClick(2)">
                <div class="day2-bg layer"></div>
                <div class="day2-text layer">
                  <span>Rough Brush x50</span>
                </div>
                <div class="item layer"></div>
                <div class="day2-text-2 layer">
                  <span>day 2</span>
                </div>
              </div>
              <div class="day3 layer-group" :class="getDayClass(3)" @click="handleDayClick(3)">
                <div class="day3-bg layer"></div>
                <div class="day3-text layer">
                  <span>Fine Clay x1</span>
                </div>
                <div class="item-2 layer"></div>
                <div class="day3-text-2 layer">
                  <span>day 3</span>
                </div>
              </div>
              <div class="day4 layer-group" :class="getDayClass(4)" @click="handleDayClick(4)">
                <div class="day4-bg layer"></div>
                <div class="day4-text layer">
                  <span>Signet Ring x3</span>
                </div>
                <div class="item-3 layer"></div>
                <div class="day4-text-2 layer">
                  <span>day 4</span>
                </div>
              </div>
              <div class="day5 layer-group" :class="getDayClass(5)" @click="handleDayClick(5)">
                <div class="day5-bg layer"></div>
                <div class="day5-text layer">
                  <span>Norman Oak x10</span>
                </div>
                <div class="item-4 layer"></div>
                <div class="day5-text-2 layer">
                  <span>day 5</span>
                </div>
              </div>
            </div>
            <div class="day6-row v-row">
              <div class="day6 layer-group" :class="getDayClass(6)" @click="handleDayClick(6)">
                <div class="day6-bg layer"></div>
                <div class="day6-text layer">
                  <span>Genesis Shovel x1</span>
                </div>
                <div class="item-5 layer"></div>
                <div class="day6-text-2 layer">
                  <span>day 6</span>
                </div>
              </div>
              <div class="day7 layer-group" :class="getDayClass(7)" @click="handleDayClick(7)">
                <div class="day7-bg layer"></div>
                <div class="gem-2 layer">
                  <span>Diamond x100</span>
                </div>
                <div class="item-6 layer"></div>
                <div class="day7-text layer">
                  <span>day 7</span>
                </div>
              </div>
              <div class="day8 layer-group" :class="getDayClass(8)" @click="handleDayClick(8)">
                <div class="day8-bg layer"></div>
                <div class="day8-text layer">
                  <span>Copper Axis x1</span>
                </div>
                <div class="item-8 layer"></div>
                <div class="day8-text-2 layer">
                  <span>day 8</span>
                </div>
              </div>
              <div class="day9 layer-group" :class="getDayClass(9)" @click="handleDayClick(9)">
                <div class="day9-bg layer"></div>
                <div class="day9-text layer">
                  <span>
Humanities                     <br />
Shovel x1                  </span>
                </div>
                <div class="item-9 layer"></div>
                <div class="day9-text-2 layer">
                  <span>day 9</span>
                </div>
              </div>
              <div class="day10 layer-group" :class="getDayClass(10)" @click="handleDayClick(10)">
                <div class="day10-bg layer"></div>
                <div class="gem-3 layer">
                  <span>Diamond x300</span>
                </div>
                <div class="item-7 layer"></div>
                <div class="day10-text layer">
                  <span>day 10</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="progress layer-group v-col">
        <div class="progress-bg-4 layer-group is-clickable" :class="dailyCheckinButtonClass" @click="handleDailyCheckin">
          <div class="bg-section layer-group">
            <div class="rect-8 layer"></div>
            <div class="rect-2-4 layer"></div>
            <div class="rect-3-4 layer"></div>
          </div>
          <div class="check layer"></div>
          <div class="btn-checkin-3 layer"></div>
          <div class="checkin-days-overlay">
            <i18n-t keypath="checkin.checkedDays" tag="span">
              <template #days>
                <span class="checkin-days-count">{{ checkedDays }}</span>
              </template>
            </i18n-t>
          </div>
        </div>
        <div class="reward-3-row v-row">
          <div class="reward-3 layer-group is-clickable" :class="milestone7Class" @click="handleMilestoneClaim(7)">
            <div class="rect-9 layer"></div>
            <div class="reward-text layer">
              <span>
Fine Clay x3                <br />
              </span>
            </div>
            <div class="item-10 layer"></div>
          </div>
          <div class="reward-2-2 layer-group is-clickable" :class="milestone10Class" @click="handleMilestoneClaim(10)">
            <div class="rect-10 layer"></div>
            <div class="reward-text-2 layer">
              <span>
Genesis                 <br />
Shovel x3                <br />
              </span>
            </div>
            <div class="item-11 layer"></div>
          </div>
        </div>
        <div class="item-12-row v-row">
          <div class="item-12 layer"></div>
          <div class="btn-go layer"></div>
        </div>
        <div class="progress-bg-2-stack v-stack">
          <div class="progress-bg-2 layer-group">
            <div class="group layer-group">
              <div class="ellipse layer"></div>
              <div class="ellipse-2-2 layer"></div>
              <div class="ellipse-3-2 layer"></div>
            </div>
            <div class="rating layer is-clickable" :class="milestone7Class" @click="handleMilestoneClaim(7)"></div>
          </div>
          <div class="progress-bg-3 layer-group">
            <div class="group-2 layer-group">
              <div class="ellipse-2 layer"></div>
              <div class="ellipse-2-3 layer"></div>
              <div class="ellipse-3-3 layer"></div>
            </div>
            <div class="rating-2 layer is-clickable" :class="milestone10Class" @click="handleMilestoneClaim(10)"></div>
          </div>
          <div class="progress-bg layer-group">
            <div class="bg-section-2 layer-group v-row">
              <div class="triangle layer"></div>
              <div class="rect-11 layer"></div>
              <div class="triangle-2-2 layer"></div>
            </div>
            <div class="rect-12 layer"></div>
            <div class="rect-2-5 layer" :style="progressBarStyle"></div>
          </div>
        </div>
        <div class="progress-text-row v-row">
          <div class="progress-text layer">
            <span>Total</span>
          </div>
          <div class="progress-text-2 layer">
            <span>7 Times</span>
          </div>
          <div class="progress-text-3 layer">
            <span>10 Times</span>
          </div>
        </div>
      </div>
      <div class="btn-checkin-4 layer-group">
        <div class="btn-checkin-5 layer"></div>
        <div class="btn-checkin-2-2 layer"></div>
      </div>
    </div>
    <div class="zhuanpanhuo layer-group v-col">
      <div class="title-2 layer-group">
        <div class="title-icon layer"></div>
        <div class="title-text-2 layer">
          <span>{{ t('event.duration', { range: eventDurationText }) }}</span>
        </div>
      </div>
      <div class="btn-draw-3-stack v-stack">
        <div class="btn-draw-3 layer-group v-row">
          <div class="btn-draw-text layer">
            <span>{{ t('wheel.tickets') }}</span>
          </div>
          <div class="btn-draw-text-2 layer">
            <span>{{ tickets }}</span>
          </div>
        </div>
        <div class="zhuanpanhuo-icon-host layer" aria-hidden="true">
          <img
            class="wheel-stand"
            :src="wheelStandImg"
            width="750"
            height="729"
            alt=""
            draggable="false"
          />
          <div
            ref="rotatorRef"
            class="wheel-disc-stage"
            :class="{ 'is-wheel-spinning': isWheelSpinning }"
            :style="wheelIconStyle"
          >
            <img
              class="wheel-disc"
              :src="wheelDiscImg"
              width="465"
              height="465"
              alt=""
              draggable="false"
            />
          </div>
          <img
            class="wheel-frame"
            :src="wheelFrameImg"
            width="750"
            height="729"
            alt=""
            draggable="false"
          />
          <img
            class="wheel-character"
            :src="wheelCharacterImg"
            width="750"
            height="729"
            alt=""
            draggable="false"
          />
        </div>
      </div>
      <div class="zhuanpanhuo-text layer is-clickable" @click="handleTicketHistoryClick">
        <span>{{ t('wheel.ticketHistory') }}</span>
      </div>
      <div class="win layer is-clickable" @click="handleWinHistoryClick">
        <span>{{ t('wheel.winningRecords') }}</span>
      </div>
      <div class="btn-draw-row v-row">
        <div class="btn-draw layer-group is-clickable" :class="{ 'is-wheel-disabled': isWheelSpinning }" @click="handleSpinX1">
          <div class="btn-draw-bg layer"></div>
          <div class="btn-draw-icon layer"></div>
        </div>
        <div class="btn-draw-2 layer-group is-clickable" :class="{ 'is-wheel-disabled': isWheelSpinning }" @click="handleSpinX10">
          <div class="btn-draw-bg-2 layer"></div>
          <div class="btn-draw-icon-2 layer"></div>
        </div>
      </div>
      <div class="rules layer-group">
        <div class="rules-2 layer"></div>
        <div class="rules-2-2 layer"></div>
      </div>
    </div>
    <div class="limited layer-group">
      <div class="title-3 layer-group">
        <div class="bg-section-4 layer-group v-col">
          <div class="title-4 layer-group">
            <div class="reward-4 layer"></div>
            <div class="title-text-3 layer">
              <span>{{ t('event.duration', { range: eventDurationText }) }}</span>
            </div>
          </div>
          <div class="progress-2 layer-group v-col">
            <div class="prize layer-group v-row">
              <div class="reward-5-stack v-stack" :class="getTopupTierClass(499)" @click="handleTopupTierClaim(499)">
                <div class="reward-5 layer-group">
                  <div class="triangle-2 layer"></div>
                  <div class="bubble layer">
                    <span>Chat Bubble x1</span>
                  </div>
                </div>
                <div class="prize-2 layer"></div>
              </div>
              <div class="reward-2-3-stack v-stack" :class="getTopupTierClass(999)" @click="handleTopupTierClaim(999)">
                <div class="reward-2-3 layer-group">
                  <div class="triangle-3 layer"></div>
                  <div class="reward-text-3 layer">
                    <span>Fine Clay x5</span>
                  </div>
                </div>
                <div class="prize-2-2 layer"></div>
              </div>
              <div class="prize-3 layer" :class="getTopupTierClass(1999)" @click="handleTopupTierClaim(1999)"></div>
              <div class="prize-4 layer" :class="getTopupTierClass(2999)" @click="handleTopupTierClaim(2999)"></div>
              <div class="prize-5 layer" :class="getTopupTierClass(4999)" @click="handleTopupTierClaim(4999)"></div>
              <div class="prize-6 layer" :class="getTopupTierClass(9999)" @click="handleTopupTierClaim(9999)"></div>
            </div>
            <div class="progress-bg-2-2-stack v-stack">
              <div class="progress-bg-2-2 layer-group v-col">
                <div class="img-6-2-row v-row">
                  <div class="img-6-2 layer"></div>
                  <div class="text-5 layer">
                    <span>499</span>
                  </div>
                  <div class="img-4-2 layer"></div>
                  <div class="text-3 layer">
                    <span>999</span>
                  </div>
                  <div class="img-5-2 layer"></div>
                  <div class="text-4 layer">
                    <span>1999</span>
                  </div>
                  <div class="img-7-2 layer"></div>
                  <div class="text-6 layer">
                    <span>2999</span>
                  </div>
                  <div class="img-9 layer"></div>
                  <div class="text-7 layer">
                    <span>4999</span>
                  </div>
                  <div class="img-8 layer"></div>
                  <div class="text-8 layer">
                    <span>9999</span>
                  </div>
                </div>
                <div class="item-2-2-row v-row">
                  <div class="item-2-2 layer" :class="{ 'is-topup-chest-reached': totalTopup > 0 }"></div>
                  <div class="item-3-2 layer" :class="{ 'is-topup-chest-reached': totalTopup >= 499 }"></div>
                  <div class="item-4-2 layer" :class="{ 'is-topup-chest-reached': totalTopup >= 999 }"></div>
                  <div class="img-2-2 layer" :class="{ 'is-topup-chest-reached': totalTopup >= 1999 }"></div>
                  <div class="item-5-2 layer" :class="{ 'is-topup-chest-reached': totalTopup >= 2999 }"></div>
                  <div class="img-3-3 layer" :class="{ 'is-topup-chest-reached': totalTopup >= 4999 }"></div>
                  <div class="item-13 layer" :class="{ 'is-topup-chest-reached': totalTopup >= 9999 }"></div>
                </div>
                <div class="text-row v-row">
                  <div class="text layer">
                    <span>{{ t('topup.totalTopup') }}</span>
                  </div>
                  <div class="img-3 layer"></div>
                  <div class="text-2 layer">
                    <span>{{ totalTopup }}</span>
                  </div>
                </div>
              </div>
              <div class="progress-bg-5 layer-group">
                <div class="bg-section-3 layer-group v-row">
                  <div class="triangle-4 layer"></div>
                  <div class="rect-13 layer"></div>
                  <div class="triangle-2-3 layer"></div>
                </div>
                <div class="rect-14 layer"></div>
                <div class="rect-2-6 layer" :style="topupProgressBarStyle"></div>
              </div>
            </div>
          </div>
          <div class="click-to-visit-the-o layer is-clickable" @click="handleTopupCenterClick">
            <span>{{ t('topup.visitCenter') }}</span>
          </div>
          <div class="rules-3 layer-group">
            <div class="rules-4 layer"></div>
            <div class="reward-6 layer"></div>
          </div>
        </div>
      </div>
    </div>
    <div class="huawenfen layer-group">
      <div class="huawenfen-icon layer"></div>
      <div class="shape layer"></div>
      <div class="huawenfen-icon-2 layer"></div>
      <div class="huawenfen-icon-3 layer"></div>
      <div class="huawenfen-icon-4 layer"></div>
      <div class="shape-2 layer"></div>
    </div>
    <div class="nav layer-group v-col">
      <div class="rect-15-stack v-stack">
        <div class="rect-15 layer"></div>
        <div class="logo layer"></div>
        <div class="rect-2-7 layer"></div>
        <div class="nav-menu-hits">
          <button
            type="button"
            class="nav-menu-hit nav-menu-hit--checkin"
            :aria-label="t('nav.checkinEvent')"
            @click="scrollToSection('checkin')"
          ></button>
          <button
            type="button"
            class="nav-menu-hit nav-menu-hit--topup"
            :aria-label="t('nav.topupRewards')"
            @click="scrollToSection('topup')"
          ></button>
          <button
            type="button"
            class="nav-menu-hit nav-menu-hit--wheel"
            :aria-label="t('nav.luckyWheel')"
            @click="scrollToSection('wheel')"
          ></button>
        </div>
        <div class="nav-bg-3 layer-group is-clickable" @click.stop="toggleLanguageMenu">
          <div class="rounded-3 layer"></div>
          <div class="rect-16 layer"></div>
          <div class="english layer">
            <span>{{ currentLanguageLabel }}</span>
          </div>
          <div class="duobianxing layer"></div>
          <div class="yingyu layer"></div>
          <LanguageMenu
            v-if="languageMenuVisible"
            class="mobile-language-menu"
            :options="languageOptions"
            :current-locale="locale"
            @select="selectLanguage"
            @close="languageMenuVisible = false"
          />
        </div>
        <div class="nav-bg layer-group is-clickable" @click="handleLoginClick">
          <div class="rect-17 layer"></div>
          <div class="login layer">
            <span>{{ userStore.isLoggedIn ? userStore.displayName : t('nav.login') }}</span>
          </div>
        </div>
      </div>
      <div class="btn-confirm-row v-row">
        <div class="btn-confirm layer-group is-clickable" @click="handleFacebookClick">
          <div class="ellipse-3 layer"></div>
          <div class="btn-confirm-2 layer"></div>
        </div>
        <div class="nav-bg-2 layer-group is-clickable" @click="handleDiscordClick">
          <div class="ellipse-4 layer"></div>
          <div class="discord layer"></div>
        </div>
      </div>
    </div>
    <div class="dibu layer-group">
      <div class="dibu-icon layer"></div>
      <div class="dibu-icon-2 layer"></div>
      <div class="dibu-icon-3 layer"></div>
      <div class="dibu-icon-4 layer"></div>
      <div class="dibu-icon-5 layer"></div>
      <div class="dibu-icon-6 layer"></div>
      <div class="dibu-icon-7 layer"></div>
      <div class="dibu-icon-8 layer"></div>
      <div class="limited-2 layer">
        <span>
          <a class="footer-link" href="#" @click.prevent="openFooterLink('privacy')">{{ t('footer.privacy') }}</a>
          |
          <a class="footer-link" href="#" @click.prevent="openFooterLink('terms')">{{ t('footer.terms') }}</a>
          <br />
          {{ t('footer.copyright') }}
        </span>
      </div>
    </div>
  </div>
  </div>
  <AppToast />
  <AppLoading />
  <CharacterSelectModal />
  <RewardHistoryModal />
  <TicketHistoryModal />
  <WinHistoryModal />
  <SpinResultModal />
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref, watch } from 'vue'
import { storeToRefs } from 'pinia'
import { useI18n } from 'vue-i18n'
import AppLoading from './components/AppLoading.vue'
import AppToast from './components/AppToast.vue'
import CharacterSelectModal from './components/CharacterSelectModal.vue'
import LanguageMenu from './components/LanguageMenu.vue'
import RewardHistoryModal from './components/RewardHistoryModal.vue'
import SpinResultModal from './components/SpinResultModal.vue'
import TicketHistoryModal from './components/TicketHistoryModal.vue'
import WinHistoryModal from './components/WinHistoryModal.vue'
import { useCheckinActions } from './composables/useCheckinActions'
import { useCheckinCarousel } from './composables/useCheckinCarousel'
import { useGlobalActions } from './composables/useGlobalActions'
import { useSectionNav } from './composables/useSectionNav'
import { useTopupActions } from './composables/useTopupActions'
import { useUtc5Clock } from './composables/useUtc5Clock'
import { useWheelActions } from './composables/useWheelActions'
import { LANGUAGE_OPTIONS, persistLocale } from './i18n'
import { useActivityStore } from './stores/activity'
import { useUserStore } from './stores/user'
import { ExternalLinks, openExternalLink } from './utils/links'
import wheelDiscImg from './assets/images/wheel-disc.png'
import wheelStandImg from './assets/images/wheel-stand.png'
import wheelFrameImg from './assets/images/wheel-frame.png'
import wheelCharacterImg from './assets/images/wheel-character.png'
import { isInGameKitWebView, resolveLoginToken } from './bridge/auth.js'
import { fetchSdkGameRole } from './bridge/role.js'

const { t, locale } = useI18n()
const activityStore = useActivityStore()
const userStore = useUserStore()

async function trySelectRoleFromSdk() {
  try {
    const sdkRole = await fetchSdkGameRole()
    if (!sdkRole?.roleId) return

    await userStore.selectRole(sdkRole.roleId)
  } catch (e) {
    console.warn('[SDK] auto select role failed', e)
    // 失败则仍走手动选角
  }
}
const { eventDurationText } = storeToRefs(activityStore)

const {
  handleLoginClick,
  handleFacebookClick,
  handleDiscordClick,
} = useGlobalActions()

const {
  checkedDays,
  progressBarStyle,
  dailyCheckinButtonClass,
  milestone7Class,
  milestone10Class,
  getDayClass,
  refreshCheckinStatus,
  handleDailyCheckin,
  handleDayClick,
  handleMilestoneClaim,
  handleRewardHistoryClick,
} = useCheckinActions()

const {
  tickets,
  wheelRotation,
  isWheelSpinning,
  rotatorRef,
  refreshWheelInfo,
  handleSpinX1,
  handleSpinX10,
  handleTicketHistoryClick,
  handleWinHistoryClick,
} = useWheelActions()

const wheelIconStyle = computed(() => ({
  transform: `rotate(${wheelRotation.value}deg)`,
}))

const { currentUtc5Text, syncServerOffset } = useUtc5Clock()
const { carouselImageStyle, showPrev: showCarouselPrev, showNext: showCarouselNext } = useCheckinCarousel()

const {
  totalTopup,
  topupProgressBarStyle,
  getTierClass: getTopupTierClass,
  refreshTopupProgress,
  handleTierClaim: handleTopupTierClaim,
  handleTopupCenterClick,
} = useTopupActions()

const DESIGN_WIDTH = 750
const DESIGN_HEIGHT = 5083
const scale = ref(1)

const { scrollToSection } = useSectionNav(scale)

function updateScale() {
  const w = window.visualViewport?.width ?? window.innerWidth
  scale.value = w / DESIGN_WIDTH
}

const viewportStyle = computed(() => ({
  height: `${DESIGN_HEIGHT * scale.value}px`,
}))

const canvasStyle = computed(() => ({
  transform: `scale(${scale.value})`,
}))

const languageMenuVisible = ref(false)
const languageOptions = LANGUAGE_OPTIONS
const currentLanguageLabel = computed(
  () => languageOptions.find((item) => item.code === locale.value)?.label ?? 'English',
)

function toggleLanguageMenu() {
  languageMenuVisible.value = !languageMenuVisible.value
}

/** @param {string} code */
function selectLanguage(code) {
  locale.value = code
  persistLocale(code)
  languageMenuVisible.value = false
}

/** @param {'privacy' | 'terms'} type */
function openFooterLink(type) {
  if (type === 'privacy') openExternalLink(ExternalLinks.PRIVACY)
  if (type === 'terms') openExternalLink(ExternalLinks.TERMS)
}

watch(
  () => userStore.canParticipate,
  (canParticipate) => {
    if (canParticipate) {
      refreshCheckinStatus()
      refreshWheelInfo()
      refreshTopupProgress()
    }
  },
  { immediate: true },
)

watch(
  () => userStore.role?.roleId,
  (roleId, prevRoleId) => {
    if (roleId && roleId !== prevRoleId && userStore.canParticipate) {
      refreshCheckinStatus()
      refreshWheelInfo()
      refreshTopupProgress()
    }
  },
)

async function bootstrapAppData() {
  try {
    // 自动登录：WebView 用 SDK token，浏览器用 URL player_token / env token / localStorage
    if (!userStore.isLoggedIn) {
      try {
        const token = await resolveLoginToken()
        if (token) {
          await userStore.login({ accessToken: token })
        }
      } catch (e) {
        console.warn('[auto-login] failed', e)
      }
    }

    await Promise.all([
      activityStore.loadInfo(),
      userStore.loadSession(),
    ])
    syncServerOffset()

    if (isInGameKitWebView() && userStore.isLoggedIn && !userStore.hasRole) {
      await trySelectRoleFromSdk()
    }
  } catch (error) {
    console.error('[bootstrap] failed to load initial data', error)
  }
}

/** @param {MouseEvent} event */
function handleDocumentClick(event) {
  const target = event.target
  if (!(target instanceof Element)) return
  if (target.closest('.nav-bg-3') || target.closest('.language-menu')) return
  languageMenuVisible.value = false
}

onMounted(() => {
  updateScale()
  bootstrapAppData()
  window.addEventListener('resize', updateScale)
  window.visualViewport?.addEventListener('resize', updateScale)
  document.addEventListener('click', handleDocumentClick)
})

onUnmounted(() => {
  window.removeEventListener('resize', updateScale)
  window.visualViewport?.removeEventListener('resize', updateScale)
  document.removeEventListener('click', handleDocumentClick)
})
</script>

<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
.is-clickable {
  cursor: pointer;
}
.footer-link {
  color: inherit;
  text-decoration: none;
  cursor: pointer;
}
.login {
  white-space: nowrap;
}
.login span {
  max-width: 110px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
.svg-filters {
  position: absolute;
  width: 0;
  height: 0;
  overflow: hidden;
  pointer-events: none;
}
.english {
  overflow: visible;
  white-space: nowrap;
}
body {
    width: 100%;
    min-height: 100vh;
    overflow-x: hidden;
    overflow-y: auto;
    background: #f0f0f0;
    -webkit-text-size-adjust: 100%;
}

.scale-viewport {
  width: 100%;
  overflow: hidden;
  touch-action: pan-y;
}

#canvas {
  position: relative;
  transform-origin: top left;
  display: flex;
  flex-direction: column;
  width: 750px;
  height: 5083px;
  overflow: hidden;
  background: #fff;
}

.bg {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 1;
  width: 750px;
  height: 5083px;
  background: url("./assets/images/bg-3bdb0f.png") no-repeat;
}
.shouye { position: absolute; left: 0px; top: 0px; z-index: 4; width: 752px; height: 3847px; }
.home-cat-hits {
  position: absolute;
  left: 0;
  top: 0;
  z-index: 6;
  width: 750px;
  height: 900px;
  pointer-events: none;
}
.home-cat-hit {
  position: absolute;
  top: 772px;
  height: 56px;
  padding: 0;
  border: 0;
  background: transparent;
  pointer-events: auto;
  cursor: pointer;
}
.home-cat-hit--checkin { left: 20px; width: 230px; }
.home-cat-hit--topup { left: 262px; width: 226px; }
.home-cat-hit--wheel { left: 496px; width: 228px; }
.shouye-bg {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 2;
  width: 750px;
  height: 3845px;
  background: url("./assets/images/shouye-5fa316.png") no-repeat;
}
.shouye-icon {
  position: absolute;
  left: 56px;
  top: 618px;
  z-index: 3;
  width: 639px;
  height: 161px;
  background: url("./assets/images/yingwen-c463c4.png") no-repeat;
}
.bg-2 {
  position: absolute;
  left: 0px;
  top: 900px;
  z-index: 18;
  display: flex;
  flex-direction: column;
  width: 750px;
  height: 4183px;
  padding-top: 626px;
  background: url("./assets/images/bg-3540ba.png") 0% 0%/100% 100% no-repeat;
}
.mousi-row {
  z-index: 0;
  display: flex;
  flex-direction: row;
  width: 734px;
  height: 147px;
  margin-left: 9px;
  flex-shrink: 0;
}
.mousi { width: 106px; height: 138px; margin-top: 9px; background: url("./assets/images/mousi-c2c325.png") no-repeat; }
.ludewei { width: 113px; height: 146px; margin-left: 515px; background: url("./assets/images/ludewei-f4b883.png") no-repeat; }
.rect { width: 750px; height: 378px; margin-top: -5px; background: url("./assets/images/rect-c6d4c0.png") no-repeat; }
.img-6 { width: 370px; height: 103px; margin-top: 146px; background: url("./assets/images/img-4ff133.png") no-repeat; opacity: 0.71; }
.img-7 { width: 229px; height: 163px; margin-top: 283px; margin-left: 521px; background: url("./assets/images/img-e10d09.png") no-repeat; }
.bg-2-2-stack { position: relative; z-index: 16; width: 750px; height: 701px; margin-top: -40px; flex-shrink: 0; }
.bg-2-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 7;
  width: 750px;
  height: 701px;
  background: url("./assets/images/bg-ef752a.png") no-repeat;
}
.linshiyan {
  position: absolute;
  left: 0px;
  top: 163px;
  z-index: 12;
  width: 750px;
  height: 273px;
  background: url("./assets/images/linshiyan-c7da8e.png") no-repeat;
}
.img-2 { width: 58px; height: 174px; margin-top: 57px; background: url("./assets/images/img-d30887.png") no-repeat; }
.img-stack { position: relative; z-index: 17; width: 750px; height: 823px; margin-top: -58px; flex-shrink: 0; }
.img {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 6;
  width: 723px;
  height: 767px;
  background: url("./assets/images/img-f0adba-trim-8561c1.png") no-repeat;
}
.img-3-2 {
  position: absolute;
  left: 633px;
  top: 0px;
  z-index: 9;
  width: 117px;
  height: 123px;
  background: url("./assets/images/img-c4d049.png") no-repeat;
}
.img-5 {
  position: absolute;
  left: 0px;
  top: 658px;
  z-index: 11;
  width: 131px;
  height: 164px;
  background: url("./assets/images/img-209fdc.png") no-repeat;
}
.img-4 {
  position: absolute;
  left: 0px;
  top: 698px;
  z-index: 10;
  width: 131px;
  height: 125px;
  background: url("./assets/images/img-b94c3e.png") no-repeat;
}
.slogan-checkin {
  position: absolute;
  left: 33px;
  top: 1039px;
  z-index: 141;
  display: flex;
  flex-direction: column;
  width: 709px;
  height: 1507px;
}
.title {
  display: flex;
  flex-direction: column;
  width: 601px;
  height: 87px;
  margin-left: 43px;
  flex-shrink: 0;
  overflow: visible;
}
.btn-checkin {
  width: 599px;
  height: 48px;
  min-height: 48px;
  flex-shrink: 0;
  background: url("./assets/images/btn-checkin-6140b1.png") no-repeat center / 100% 100%;
}
.title-text {
  width: 560px;
  height: auto;
  min-height: 22px;
  margin-top: 16px;
  margin-left: 20px;
  color: rgba(123, 84, 16, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  line-height: 22px;
  text-align: left;
}
.checkin-frame { display: flex; flex-direction: column; width: 589px; height: 407px; margin-top: 22px; margin-left: 53px; }
.rect-2-stack { position: relative; z-index: 0; width: 593px; height: 370px; flex-shrink: 0; }
.rect-2 {
  position: absolute;
  left: 24px;
  top: 0px;
  z-index: 123;
  width: 528px;
  height: 370px;
  background: url("./assets/images/rect-0ac860.png") no-repeat;
}
.rect-2-2 {
  position: absolute;
  left: 31px;
  top: 6px;
  z-index: 130;
  width: 513px;
  height: 320px;
  background: url("./assets/images/rect-36432d.png") no-repeat;
}
.rect-3-2 {
  position: absolute;
  left: 36px;
  top: 6px;
  z-index: 131;
  width: 510px;
  height: 317px;
  background: url("./assets/images/rect-f0c59c.png") no-repeat;
}
.role { position: absolute; left: 36px; top: 11px; z-index: 134; width: 513px; height: 318px; }
.rect-3 {
  position: absolute;
  left: -4px;
  top: -4px;
  z-index: 132;
  width: 511px;
  height: 316px;
  background: url("./assets/images/rect-b80747.png") no-repeat;
}
.role-2 {
  position: absolute;
  left: -3px;
  top: -3px;
  z-index: 133;
  width: 509px;
  height: 314px;
  background: url("./assets/images/role-45516c.png") no-repeat;
}
.arrow { position: absolute; left: 0px; top: 143px; z-index: 126; width: 67px; height: 64px; }
.rect-4 {
  position: absolute;
  left: -6px;
  top: -6px;
  z-index: 124;
  width: 65px;
  height: 62px;
  background: url("./assets/images/rect-00370d.png") no-repeat;
}
.rounded {
  position: absolute;
  left: 10px;
  top: 10px;
  z-index: 125;
  width: 22px;
  height: 31px;
  background: url("./assets/images/rounded-b70a65.png") no-repeat;
}
.arrow-2 { position: absolute; left: 526px; top: 143px; z-index: 129; width: 67px; height: 64px; }
.rect-5 {
  position: absolute;
  left: -6px;
  top: -6px;
  z-index: 127;
  width: 65px;
  height: 62px;
  background: url("./assets/images/rect-9759cc.png") no-repeat;
}
.rounded-2 {
  position: absolute;
  left: 21px;
  top: 10px;
  z-index: 128;
  width: 22px;
  height: 31px;
  background: url("./assets/images/rounded-3ecc3e.png") no-repeat;
}
.checkin-frame-text {
  position: absolute;
  left: 24px;
  top: 334px;
  z-index: 135;
  width: 528px;
  height: 24px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: rgba(246, 233, 211, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  line-height: 24px;
  text-align: center;
  white-space: nowrap;
}
.reward {
  width: auto;
  max-width: 100%;
  height: 22px;
  margin-top: 17px;
  margin-left: auto;
  margin-right: 20px;
  align-self: flex-end;
  color: rgba(222, 91, 70, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  font-weight: 700;
  line-height: 22px;
  text-align: right;
  text-decoration: underline;
  white-space: nowrap;
  cursor: pointer;
}
.reward-2 { display: flex; flex-direction: column; width: 620px; height: 444px; margin-top: 31px; margin-left: 39px; }
.reward-bg-3-stack { position: relative; z-index: 0; width: 478px; height: 69px; margin-left: 65px; flex-shrink: 0; }
.reward-bg-3 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 120;
  display: flex;
  flex-direction: row;
  width: 478px;
  height: 69px;
}
.rect-6 { width: 44px; height: 56px; margin-top: 8px; background: url("./assets/images/rect-ff0bb9.png") no-repeat; }
.rect-2-3 { width: 44px; height: 55px; margin-top: 12px; margin-left: 388px; background: url("./assets/images/rect-3d35e7.png") no-repeat; }
.rect-3-3 {
  position: absolute;
  left: 24px;
  top: 0px;
  z-index: 119;
  width: 429px;
  height: 58px;
  background: url("./assets/images/rect-019fb8.png") no-repeat;
}
.btn-checkin-2 {
  position: absolute;
  left: 24px;
  top: 0;
  z-index: 121;
  width: 429px;
  height: 58px;
  display: flex;
  align-items: center;
  justify-content: center;
  box-sizing: border-box;
  padding: 0 20px;
  color: rgba(165, 104, 72, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
  font-weight: 700;
  line-height: 1.15;
  text-align: center;
}
.reward-bg-2-stack { position: relative; z-index: 1; width: 618px; height: 335px; margin-top: 38px; flex-shrink: 0; }
.reward-bg-2 { display: none; }
.rect-7 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 115;
  width: 120px;
  height: 165px;
  background: url("./assets/images/rect-875f99.png") no-repeat;
}
.reward-bg {
  position: absolute;
  left: 6px;
  top: 6px;
  z-index: 113;
  display: flex;
  flex-direction: column;
  width: 612px;
  height: 329px;
}
.yingwen-row { z-index: 0; display: flex; flex-direction: row; width: 612px; height: 163px; flex-shrink: 0; }
.yingwen-stack { position: relative; z-index: 0; width: 106px; height: 151px; flex-shrink: 0; }
.yingwen {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 67;
  width: 106px;
  height: 151px;
  background: url("./assets/images/yingwen-4f2eb2-trim-b11005.png") no-repeat;
}
.day1 {
  position: absolute;
  left: 15px;
  top: 15px;
  z-index: 66;
  display: flex;
  flex-direction: column;
  width: 78px;
  height: 123px;
}
.day1-text { width: 54px; height: 14px; margin-left: 13px; color: rgba(229, 181, 13, 1); font-size: 11.9px; text-align: center; }
.gem { width: 78px; height: 9px; margin-top: 100px; color: rgba(255, 255, 255, 1); font-size: 7.65px; text-align: center; }
.day2 { position: relative; z-index: 72; width: 118px; height: 163px; margin-left: 18px; flex-shrink: 0; }
.day2-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 68;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day2-b40e4b.png") no-repeat;
}
.day2-text {
  position: absolute;
  left: 8px;
  top: 129px;
  z-index: 69;
  width: 92px;
  height: 11px;
  color: rgba(255, 255, 255, 1);
  font-size: 9.35px;
  text-align: center;
}
.item {
  position: absolute;
  left: 14px;
  top: 40px;
  z-index: 70;
  width: 79px;
  height: 66px;
  background: url("./assets/images/item-cb8c68.png") no-repeat;
}
.day2-text-2 {
  position: absolute;
  left: 26px;
  top: 15px;
  z-index: 71;
  width: 56px;
  height: 14px;
  color: rgba(187, 153, 89, 1);
  font-size: 11.9px;
  text-align: center;
}
.day3 { position: relative; z-index: 77; width: 118px; height: 163px; margin-left: 5px; flex-shrink: 0; }
.day3-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 73;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day3-aa0ef2.png") no-repeat;
}
.day3-text {
  position: absolute;
  left: 22px;
  top: 129px;
  z-index: 74;
  width: 63px;
  height: 11px;
  color: rgba(255, 255, 255, 1);
  font-size: 9.35px;
  text-align: center;
}
.item-2 {
  position: absolute;
  left: 17px;
  top: 37px;
  z-index: 75;
  width: 74px;
  height: 74px;
  background: url("./assets/images/item-1df5ed.png") no-repeat;
}
.day3-text-2 {
  position: absolute;
  left: 27px;
  top: 15px;
  z-index: 76;
  width: 56px;
  height: 14px;
  color: rgba(187, 153, 89, 1);
  font-size: 11.9px;
  text-align: center;
}
.day4 { position: relative; z-index: 82; width: 118px; height: 163px; margin-left: 5px; flex-shrink: 0; }
.day4-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 78;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day4-806614.png") no-repeat;
}
.day4-text {
  position: absolute;
  left: 15px;
  top: 129px;
  z-index: 79;
  width: 78px;
  height: 11px;
  color: rgba(255, 255, 255, 1);
  font-size: 9.35px;
  text-align: center;
}
.item-3 {
  position: absolute;
  left: 22px;
  top: 41px;
  z-index: 80;
  width: 64px;
  height: 65px;
  background: url("./assets/images/item-410956.png") no-repeat;
}
.day4-text-2 {
  position: absolute;
  left: 27px;
  top: 15px;
  z-index: 81;
  width: 56px;
  height: 14px;
  color: rgba(187, 153, 89, 1);
  font-size: 11.9px;
  text-align: center;
}
.day5 { position: relative; z-index: 87; width: 118px; height: 163px; margin-left: 6px; flex-shrink: 0; }
.day5-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 83;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day5-c70c77.png") no-repeat;
}
.day5-text {
  position: absolute;
  left: 9px;
  top: 129px;
  z-index: 84;
  width: 89px;
  height: 9px;
  color: rgba(255, 255, 255, 1);
  font-size: 7.65px;
  text-align: center;
}
.item-4 {
  position: absolute;
  left: 12px;
  top: 53px;
  z-index: 85;
  width: 80px;
  height: 46px;
  background: url("./assets/images/item-290c4b.png") no-repeat;
}
.day5-text-2 {
  position: absolute;
  left: 26px;
  top: 14px;
  z-index: 86;
  width: 56px;
  height: 15px;
  color: rgba(229, 181, 13, 1);
  font-size: 12.75px;
  text-align: center;
}
.day6-row {
  z-index: 1;
  display: flex;
  flex-direction: row;
  width: 612px;
  height: 163px;
  margin-top: 3px;
  flex-shrink: 0;
}
.day6 { position: relative; z-index: 92; width: 118px; height: 163px; flex-shrink: 0; }
.day6-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 88;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day6-04395c.png") no-repeat;
}
.day6-text {
  position: absolute;
  left: 7px;
  top: 129px;
  z-index: 89;
  width: 94px;
  height: 9px;
  color: rgba(255, 255, 255, 1);
  font-size: 7.65px;
  text-align: center;
}
.item-5 {
  position: absolute;
  left: 22px;
  top: 40px;
  z-index: 90;
  width: 65px;
  height: 70px;
  background: url("./assets/images/item-703468.png") no-repeat;
}
.day6-text-2 {
  position: absolute;
  left: 26px;
  top: 15px;
  z-index: 91;
  width: 57px;
  height: 14px;
  color: rgba(187, 153, 89, 1);
  font-size: 11.9px;
  text-align: center;
}
.day7 { position: relative; z-index: 97; width: 118px; height: 163px; margin-left: 6px; flex-shrink: 0; }
.day7-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 93;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day7-6ccd64.png") no-repeat;
}
.gem-2 {
  position: absolute;
  left: 11px;
  top: 129px;
  z-index: 94;
  width: 84px;
  height: 9px;
  color: rgba(255, 255, 255, 1);
  font-size: 7.65px;
  text-align: center;
}
.item-6 {
  position: absolute;
  left: 20px;
  top: 48px;
  z-index: 95;
  width: 66px;
  height: 56px;
  background: url("./assets/images/item-33b57a.png") no-repeat;
}
.day7-text {
  position: absolute;
  left: 27px;
  top: 15px;
  z-index: 96;
  width: 55px;
  height: 14px;
  color: rgba(187, 153, 89, 1);
  font-size: 11.9px;
  text-align: center;
}
.day8 { position: relative; z-index: 102; width: 117px; height: 163px; margin-left: 6px; flex-shrink: 0; }
.day8-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 98;
  width: 115px;
  height: 161px;
  background: url("./assets/images/day8-854d52.png") no-repeat;
}
.day8-text {
  position: absolute;
  left: 9px;
  top: 129px;
  z-index: 99;
  width: 86px;
  height: 11px;
  color: rgba(255, 255, 255, 1);
  font-size: 9.35px;
  text-align: center;
}
.item-8 {
  position: absolute;
  left: 16px;
  top: 48px;
  z-index: 100;
  width: 73px;
  height: 56px;
  background: url("./assets/images/item-d7bf3c.png") no-repeat;
}
.day8-text-2 {
  position: absolute;
  left: 26px;
  top: 15px;
  z-index: 101;
  width: 56px;
  height: 14px;
  color: rgba(187, 153, 89, 1);
  font-size: 11.9px;
  text-align: center;
}
.day9 { position: relative; z-index: 107; width: 118px; height: 163px; margin-left: 5px; flex-shrink: 0; }
.day9-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 103;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day9-32b096.png") no-repeat;
}
.day9-text {
  position: absolute;
  left: 22px;
  top: 121px;
  z-index: 104;
  width: 63px;
  height: 22px;
  color: rgba(255, 255, 255, 1);
  font-size: 9.35px;
  line-height: 11px;
  text-align: center;
}
.item-9 {
  position: absolute;
  left: 20px;
  top: 39px;
  z-index: 105;
  width: 65px;
  height: 69px;
  background: url("./assets/images/item-ae408d.png") no-repeat;
}
.day9-text-2 {
  position: absolute;
  left: 26px;
  top: 15px;
  z-index: 106;
  width: 57px;
  height: 14px;
  color: rgba(229, 181, 13, 1);
  font-size: 11.9px;
  text-align: center;
}
.day10 { position: relative; z-index: 112; width: 118px; height: 163px; margin-left: 6px; flex-shrink: 0; }
.day10-bg {
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 108;
  width: 116px;
  height: 161px;
  background: url("./assets/images/day10-8e34c8.png") no-repeat;
}
.gem-3 {
  position: absolute;
  left: 14px;
  top: 129px;
  z-index: 109;
  width: 79px;
  height: 9px;
  color: rgba(255, 255, 255, 1);
  font-size: 7.65px;
  text-align: center;
}
.item-7 {
  position: absolute;
  left: 20px;
  top: 48px;
  z-index: 110;
  width: 66px;
  height: 56px;
  background: url("./assets/images/item-33b57a.png") no-repeat;
}
.day10-text {
  position: absolute;
  left: 21px;
  top: 15px;
  z-index: 111;
  width: 66px;
  height: 14px;
  color: rgba(229, 181, 13, 1);
  font-size: 11.9px;
  text-align: center;
}
.progress { display: flex; flex-direction: column; width: 699px; height: 320px; margin-top: 56px; margin-left: 8px; }
.progress-bg-4 { position: relative; z-index: 60; width: 444px; height: 82px; margin-left: 114px; flex-shrink: 0; }
.bg-section {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 57;
  display: flex;
  flex-direction: row;
  width: 442px;
  height: 80px;
}
.rect-8 { width: 41px; height: 65px; margin-top: 13px; background: url("./assets/images/rect-39efd2.png") no-repeat; }
.rect-2-4 { width: 41px; height: 65px; margin-top: 13px; margin-left: 358px; background: url("./assets/images/rect-31a5be.png") no-repeat; }
.rect-3-4 {
  position: absolute;
  left: 28px;
  top: 0px;
  z-index: 56;
  width: 384px;
  height: 71px;
  background: url("./assets/images/rect-e70ca9.png") no-repeat;
}
.check {
  position: absolute;
  left: 61px;
  top: 42px;
  z-index: 58;
  width: 319px;
  height: 22px;
  background: url("./assets/images/check-894e0a.png") no-repeat;
}
.btn-checkin-3 {
  position: absolute;
  left: 107px;
  top: 13px;
  z-index: 59;
  width: 224px;
  height: 20px;
  background: url("./assets/images/btn-checkin-e74a0b.png") no-repeat;
}
.reward-3-row {
  z-index: 61;
  display: flex;
  flex-direction: row;
  width: 335px;
  height: 65px;
  margin-top: 27px;
  margin-left: 362px;
  flex-shrink: 0;
}
.reward-3 { position: relative; z-index: 49; width: 126px; height: 65px; flex-shrink: 0; }
.rect-9 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 46;
  width: 124px;
  height: 63px;
  background: url("./assets/images/rect-6af563.png") no-repeat;
}
.reward-text {
  position: absolute;
  left: 57px;
  top: 26px;
  z-index: 47;
  width: 56px;
  height: 10px;
  color: rgba(255, 255, 255, 1);
  font-size: 4.25px;
  line-height: 5px;
  text-align: left;
}
.item-10 {
  position: absolute;
  left: 9px;
  top: 11px;
  z-index: 48;
  width: 43px;
  height: 43px;
  background: url("./assets/images/item-1e0662.png") no-repeat;
}
.reward-2-2 { position: relative; z-index: 53; width: 125px; height: 65px; margin-left: 84px; flex-shrink: 0; }
.rect-10 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 50;
  width: 123px;
  height: 63px;
  background: url("./assets/images/rect-8d18fa.png") no-repeat;
}
.reward-text-2 {
  position: absolute;
  left: 59px;
  top: 21px;
  z-index: 51;
  width: 45px;
  height: 20px;
  color: rgba(255, 255, 255, 1);
  font-size: 5.67px;
  line-height: 6.67px;
  text-align: left;
}
.item-11 {
  position: absolute;
  left: 10px;
  top: 11px;
  z-index: 52;
  width: 40px;
  height: 44px;
  background: url("./assets/images/item-b55089.png") no-repeat;
}
.item-12-row {
  z-index: 62;
  display: flex;
  flex-direction: row;
  width: 283px;
  height: 68px;
  margin-top: 8px;
  margin-left: 393px;
  flex-shrink: 0;
}
.item-12 { width: 56px; height: 56px; margin-top: 11px; background: url("./assets/images/item-c4d802.png") no-repeat; }
.btn-go { width: 76px; height: 68px; margin-left: 151px; background: url("./assets/images/btn-go-23256b.png") no-repeat; }
.progress-bg-2-stack { position: relative; z-index: 63; width: 670px; height: 51px; margin-top: 7px; flex-shrink: 0; }
.progress-bg-2 { position: absolute; left: 407px; top: 0px; z-index: 39; width: 40px; height: 51px; }
.group { position: absolute; left: 1px; top: 24px; z-index: 37; width: 35px; height: 22px; }
.ellipse {
  position: absolute;
  left: -3px;
  top: -1px;
  z-index: 34;
  width: 33px;
  height: 20px;
  background: url("./assets/images/ellipse-5a5e8c.png") no-repeat;
}
.ellipse-2-2 {
  position: absolute;
  left: 1px;
  top: 0px;
  z-index: 35;
  width: 25px;
  height: 13px;
  background: url("./assets/images/ellipse-a258c6.png") no-repeat;
}
.ellipse-3-2 {
  position: absolute;
  left: 5px;
  top: 2px;
  z-index: 36;
  width: 16px;
  height: 9px;
  background: url("./assets/images/ellipse-725595.png") no-repeat;
}
.rating {
  position: absolute;
  left: -4px;
  top: -4px;
  z-index: 38;
  width: 38px;
  height: 38px;
  background: url("./assets/images/rating-2bf9a0.png") no-repeat;
}
.progress-bg-3 { position: absolute; left: 630px; top: 0px; z-index: 45; width: 40px; height: 51px; }
.group-2 { position: absolute; left: 1px; top: 24px; z-index: 43; width: 35px; height: 22px; }
.ellipse-2 {
  position: absolute;
  left: -3px;
  top: -1px;
  z-index: 40;
  width: 33px;
  height: 20px;
  background: url("./assets/images/ellipse-133369.png") no-repeat;
}
.ellipse-2-3 {
  position: absolute;
  left: 1px;
  top: 0px;
  z-index: 41;
  width: 25px;
  height: 13px;
  background: url("./assets/images/ellipse-c6907b.png") no-repeat;
}
.ellipse-3-3 {
  position: absolute;
  left: 5px;
  top: 2px;
  z-index: 42;
  width: 16px;
  height: 9px;
  background: url("./assets/images/ellipse-3324f6.png") no-repeat;
}
.rating-2 {
  position: absolute;
  left: -4px;
  top: -4px;
  z-index: 44;
  width: 38px;
  height: 38px;
  background: url("./assets/images/rating-4247d1.png") no-repeat;
}
.progress-bg { position: absolute; left: 0px; top: 8px; z-index: 28; width: 669px; height: 29px; }
.bg-section-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 25;
  display: flex;
  flex-direction: row;
  width: 667px;
  height: 27px;
}
.triangle { width: 13px; height: 24px; margin-top: 1px; background: url("./assets/images/triangle-f8f0ea.png") no-repeat; }
.rect-11 { width: 645px; height: 24px; margin-left: -3px; background: url("./assets/images/rect-23f14a.png") no-repeat; }
.triangle-2-2 { width: 13px; height: 24px; margin-top: 1px; margin-left: -3px; background: url("./assets/images/triangle-38470b.png") no-repeat; }
.rect-12 {
  position: absolute;
  left: 11px;
  top: 2px;
  z-index: 26;
  width: 644px;
  height: 20px;
  background: url("./assets/images/rect-71e916.png") no-repeat;
}
.rect-2-5 {
  position: absolute;
  left: 15px;
  top: 6px;
  z-index: 27;
  width: 0;
  min-width: 0;
  max-width: 635px;
  height: 12px;
  background: url("./assets/images/rect-7402ab.png") no-repeat;
  background-size: 100% 100%;
  transition: width 0.35s ease;
}
.progress-text-row {
  z-index: 64;
  display: flex;
  flex-direction: row;
  width: 646px;
  height: 15px;
  margin-top: -5px;
  margin-left: 6px;
  flex-shrink: 0;
}
.progress-text {
  width: 65px;
  height: 15px;
  color: rgba(150, 116, 68, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 14px;
  font-weight: 700;
  line-height: 15px;
  text-align: left;
  text-transform: uppercase;
}
.progress-text-2 {
  width: 73px;
  height: 15px;
  margin-left: 319px;
  color: rgba(150, 116, 68, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 14px;
  font-weight: 700;
  line-height: 15px;
  text-align: center;
  text-transform: uppercase;
}
.progress-text-3 {
  width: 83px;
  height: 15px;
  margin-left: 106px;
  color: rgba(150, 116, 68, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 14px;
  font-weight: 700;
  line-height: 15px;
  text-align: left;
  text-transform: uppercase;
}
.btn-checkin-4 { position: relative; z-index: 21; width: 685px; height: 84px; margin-top: 54px; flex-shrink: 0; }
.btn-checkin-5 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 19;
  width: 683px;
  height: 82px;
  background: url("./assets/images/btn-checkin-ee183b.png") no-repeat;
}
.btn-checkin-2-2 {
  position: absolute;
  left: 167px;
  top: 22px;
  z-index: 20;
  width: 352px;
  height: 39px;
  background: url("./assets/images/btn-checkin-f0d8ac.png") no-repeat;
}
.zhuanpanhuo {
  position: absolute;
  left: 0px;
  top: 3483px;
  z-index: 160;
  display: flex;
  flex-direction: column;
  width: 752px;
  min-height: 1225px;
  height: auto;
}
.title-2 {
  display: flex;
  flex-direction: column;
  width: 517px;
  height: 87px;
  margin-left: 117px;
  flex-shrink: 0;
  overflow: visible;
}
.title-icon {
  width: 509px;
  height: 48px;
  min-height: 48px;
  margin-left: 4px;
  flex-shrink: 0;
  background: url("./assets/images/lucky-wheel-b79190.png") no-repeat center / 100% 100%;
}
.title-text-2 {
  width: 517px;
  height: auto;
  min-height: 22px;
  margin-top: 16px;
  color: rgba(123, 84, 16, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  line-height: 22px;
  text-align: left;
}
.btn-draw-3-stack {
  position: relative;
  z-index: 160;
  width: 750px;
  height: 733px;
  margin-top: 44px;
  flex-shrink: 0;
}
.btn-draw-3 {
  position: absolute;
  left: 50%;
  top: 8px;
  z-index: 250;
  display: flex;
  flex-direction: row;
  align-items: center;
  width: auto;
  height: 26px;
  transform: translateX(-50%);
}
.btn-draw-text {
  width: auto;
  height: 22px;
  color: rgba(144, 96, 54, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  font-weight: 700;
  line-height: 22px;
  text-align: left;
  white-space: nowrap;
  text-shadow: 0 1px 0 rgba(90, 50, 16, 0.28), 0 2px 3px rgba(90, 50, 16, 0.18);
}
.btn-draw-text-2 {
  min-width: 17px;
  width: auto;
  height: 22px;
  margin-top: 0;
  margin-left: 6px;
  color: rgba(236, 129, 51, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
  font-weight: 700;
  line-height: 22px;
  text-align: left;
  text-decoration: underline;
  white-space: nowrap;
  text-shadow: 0 1px 0 rgba(90, 50, 16, 0.22), 0 2px 3px rgba(90, 50, 16, 0.16);
}
.btn-draw-text span {
  font-weight: 700;
}
.btn-draw-text-2 span {
  font-weight: 700;
  text-decoration: underline;
}
.zhuanpanhuo-icon-host {
  --wheel-pivot-x: 455px;
  --wheel-pivot-y: 345px;
  --wheel-clip-radius: 232.5px;
  position: absolute;
  left: 0px;
  top: 4px;
  z-index: 153;
  width: 750px;
  height: 729px;
  pointer-events: none;
}
.wheel-disc-stage {
  position: absolute;
  left: calc(var(--wheel-pivot-x) - var(--wheel-clip-radius));
  top: calc(var(--wheel-pivot-y) - var(--wheel-clip-radius));
  width: calc(var(--wheel-clip-radius) * 2);
  height: calc(var(--wheel-clip-radius) * 2);
  z-index: 2;
  transform-origin: center center;
  will-change: transform;
}
.wheel-disc {
  display: block;
  width: 100%;
  height: 100%;
  pointer-events: none;
  user-select: none;
}
.wheel-stand {
  position: absolute;
  inset: 0;
  z-index: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  user-select: none;
}
.wheel-frame {
  position: absolute;
  inset: 0;
  z-index: 3;
  width: 100%;
  height: 100%;
  pointer-events: none;
  user-select: none;
  transform-origin: var(--wheel-pivot-x) var(--wheel-pivot-y);
  transform: scale(0.85);
}
.wheel-character {
  position: absolute;
  inset: 0;
  z-index: 1;
  width: 100%;
  height: 100%;
  pointer-events: none;
  user-select: none;
}
.zhuanpanhuo-text {
  width: 280px;
  height: 26px;
  margin-top: 24px;
  margin-left: 390px;
  color: rgba(220, 147, 21, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: center;
  text-transform: uppercase;
  text-decoration: underline;
  white-space: nowrap;
  cursor: pointer;
}
.zhuanpanhuo-text span {
  text-decoration: underline;
}
.win {
  width: 280px;
  height: 26px;
  margin-top: 4px;
  margin-left: 390px;
  color: rgba(220, 147, 21, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
  font-weight: 700;
  line-height: 24px;
  text-align: center;
  text-transform: uppercase;
  text-decoration: underline;
  white-space: nowrap;
  cursor: pointer;
}
.win span {
  text-decoration: underline;
}
.btn-draw-row {
  z-index: 161;
  display: flex;
  flex-direction: row;
  justify-content: center;
  width: 501px;
  height: 89px;
  margin-top: 24px;
  margin-left: 125px;
  flex-shrink: 0;
}
.btn-draw {
  position: relative;
  z-index: 147;
  width: 211px;
  height: 71px;
  flex-shrink: 0;
  overflow: visible;
  cursor: pointer;
}
.btn-draw-bg {
  position: absolute;
  left: 0;
  top: 0;
  z-index: 145;
  width: 211px;
  height: 65px;
  box-sizing: border-box;
  border: 2px solid #5c3d1e;
  border-radius: 15px;
  background: linear-gradient(180deg, #f6d48a 0%, #eeb24a 48%, #e09a36 100%);
  box-shadow:
    0 6px 0 #8f540e,
    inset 0 2px 0 rgba(255, 255, 255, 0.62),
    inset 0 -2px 0 rgba(180, 110, 20, 0.22);
}
.btn-draw-icon {
  position: absolute;
  left: 51px;
  top: 15px;
  z-index: 146;
  width: 109px;
  height: 36px;
  background: url("./assets/images/spin-x1-ca745c.png") no-repeat center / 109px 36px;
  filter: url(#spin-text-knockout);
}
.btn-draw-2 {
  position: relative;
  z-index: 150;
  width: 211px;
  height: 71px;
  margin-left: 24px;
  flex-shrink: 0;
  overflow: visible;
  cursor: pointer;
}
.btn-draw-bg-2 {
  position: absolute;
  left: 0;
  top: 0;
  z-index: 148;
  width: 211px;
  height: 65px;
  box-sizing: border-box;
  border: 2px solid #5c3d1e;
  border-radius: 15px;
  background: linear-gradient(180deg, #ffd4a8 0%, #f9a652 42%, #f08a38 100%);
  box-shadow:
    0 6px 0 #913f11,
    inset 0 2px 0 rgba(255, 255, 255, 0.55),
    inset 0 -2px 0 rgba(160, 60, 10, 0.22);
}
.btn-draw-icon-2 {
  position: absolute;
  left: 40px;
  top: 15px;
  z-index: 149;
  width: 130px;
  height: 36px;
  background: url("./assets/images/spin-x10-2e3b1b.png") no-repeat center / 130px 36px;
  filter: url(#spin-text-knockout);
}
.rules {
  position: relative;
  z-index: 144;
  width: 685px;
  height: 84px;
  margin-top: 65px;
  margin-left: 33px;
  flex-shrink: 0;
}
.rules-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 142;
  width: 683px;
  height: 82px;
  background: url("./assets/images/btn-checkin-ee183b.png") no-repeat;
}
.rules-2-2 {
  position: absolute;
  left: 185px;
  top: 22px;
  z-index: 143;
  width: 315px;
  height: 39px;
  background: url("./assets/images/rules-fda2d7.png") no-repeat;
}
.limited { position: absolute; left: 30px; top: 2761px; z-index: 217; width: 698px; height: 585px; }
.title-3 { position: absolute; left: 0px; top: 0px; z-index: 216; width: 696px; height: 583px; }
.bg-section-4 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 215;
  display: flex;
  flex-direction: column;
  width: 694px;
  height: 581px;
}
.title-4 {
  display: flex;
  flex-direction: column;
  width: 637px;
  height: 87px;
  margin-left: 28px;
  flex-shrink: 0;
  overflow: visible;
}
.reward-4 {
  width: 635px;
  height: 48px;
  min-height: 48px;
  flex-shrink: 0;
  background: url("./assets/images/reward-f8757c.png") no-repeat center / 100% 100%;
}
.title-text-3 {
  width: 580px;
  height: auto;
  min-height: 22px;
  margin-top: 16px;
  margin-left: 28px;
  color: rgba(249, 219, 166, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  line-height: 22px;
  text-align: left;
}
.progress-2 { display: flex; flex-direction: column; width: 692px; height: 262px; margin-top: 54px; }
.prize { display: flex; flex-direction: row; width: 623px; height: 144px; margin-left: 71px; }
.reward-5-stack { position: relative; z-index: 0; width: 100px; height: 140px; flex-shrink: 0; }
.reward-5 { position: absolute; left: 0px; top: 0px; z-index: 198; width: 100px; height: 140px; }
.triangle-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 195;
  width: 100px;
  height: 140px;
  background: url("./assets/images/triangle-512738.png") no-repeat;
}
.bubble {
  position: absolute;
  left: 12px;
  top: 100px;
  z-index: 196;
  width: 77px;
  height: 10px;
  color: rgba(178, 133, 44, 1);
  font-size: 8.5px;
  text-align: center;
}
.prize-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 199;
  width: 100px;
  height: 140px;
  background: url("./assets/images/prize-603d43.png") no-repeat;
}
.reward-2-3-stack { position: relative; z-index: 1; width: 100px; height: 140px; margin-left: 4px; flex-shrink: 0; }
.reward-2-3 { position: absolute; left: 0px; top: 0px; z-index: 204; width: 100px; height: 140px; }
.triangle-3 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 200;
  width: 100px;
  height: 140px;
  background: url("./assets/images/triangle-9bc55f.png") no-repeat;
}
.reward-text-3 {
  position: absolute;
  left: 21px;
  top: 100px;
  z-index: 201;
  width: 60px;
  height: 11px;
  color: rgba(178, 133, 44, 1);
  font-size: 9.35px;
  text-align: center;
}
.prize-2-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 205;
  width: 100px;
  height: 140px;
  background: url("./assets/images/prize-3426dd.png") no-repeat;
}
.prize-3,
.prize-4,
.prize-5,
.prize-6 {
  position: relative;
}
.prize-3 { width: 100px; height: 140px; margin-left: 3px; background: url("./assets/images/prize-979b04.png") no-repeat; }
.prize-4 { width: 100px; height: 140px; margin-left: 4px; background: url("./assets/images/prize-6026ba.png") no-repeat; }
.prize-5 { width: 101px; height: 140px; margin-left: 4px; background: url("./assets/images/prize-737af1.png") no-repeat; }
.prize-6 { width: 100px; height: 140px; margin-left: 5px; background: url("./assets/images/prize-d95db9.png") no-repeat; }
.progress-bg-2-2-stack { position: relative; z-index: 211; width: 669px; height: 128px; margin-top: -12px; flex-shrink: 0; }
.progress-bg-2-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 194;
  display: flex;
  flex-direction: column;
  width: 669px;
  height: 128px;
}
.img-6-2-row {
  z-index: 0;
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 620px;
  height: 24px;
  margin-left: 91px;
  flex-shrink: 0;
}
.img-6-2,
.img-4-2,
.img-5-2,
.img-7-2,
.img-9,
.img-8 {
  width: 16px;
  height: 20px;
  background: url("./assets/images/img-d99bde.png") no-repeat center / contain;
  flex-shrink: 0;
}
.img-4-2 { margin-left: 46px; }
.img-5-2 { margin-left: 39px; }
.img-7-2 { margin-left: 35px; }
.img-9 { margin-left: 41px; }
.img-8 { margin-left: 37px; }
.text-5,
.text-3,
.text-4,
.text-6,
.text-7,
.text-8 {
  height: 16px;
  margin-top: 0;
  color: rgba(255, 255, 227, 1);
  font-family: "Arial Black", Arial, Helvetica, sans-serif;
  font-size: 16px;
  font-weight: 900;
  line-height: 1;
  white-space: nowrap;
  overflow: visible;
}
.text-5 { width: 40px; margin-left: 6px; text-align: center; }
.text-3 { width: 40px; margin-left: 6px; text-align: center; }
.text-4 { width: 48px; margin-left: 8px; text-align: center; }
.text-6 { width: 48px; margin-left: 6px; text-align: left; }
.text-7 { width: 48px; margin-left: 6px; text-align: left; }
.text-8 { width: 48px; margin-left: 6px; text-align: left; }
.text-5 span,
.text-3 span,
.text-4 span,
.text-6 span,
.text-7 span,
.text-8 span,
.text span,
.text-2 span {
  font-weight: 900;
}
.item-2-2-row {
  z-index: 1;
  display: flex;
  flex-direction: row;
  align-items: flex-end;
  width: 651px;
  height: 42px;
  margin-top: 10px;
  margin-left: 9px;
  flex-shrink: 0;
}
.item-2-2,
.item-3-2,
.item-4-2,
.img-2-2,
.item-5-2,
.img-3-3,
.item-13 {
  margin-top: 0;
  background-repeat: no-repeat;
  background-position: center bottom;
  background-size: contain;
  transform: scale(1.18);
  transform-origin: center bottom;
}
.item-2-2 { width: 37px; height: 36px; background-image: url("./assets/images/item-63c160.png"); }
.item-3-2 { width: 39px; height: 36px; margin-left: 51px; background-image: url("./assets/images/item-ed5f1d.png"); }
.item-4-2 { width: 41px; height: 38px; margin-left: 63px; background-image: url("./assets/images/item-d3aecf.png"); }
.img-2-2 { width: 42px; height: 39px; margin-left: 64px; background-image: url("./assets/images/img-750c48.png"); }
.item-5-2 { width: 42px; height: 40px; margin-left: 60px; background-image: url("./assets/images/item-ddac32.png"); }
.img-3-3 { width: 41px; height: 42px; margin-left: 64px; background-image: url("./assets/images/img-0d0af2.png"); }
.item-13 { width: 41px; height: 42px; margin-left: 66px; background-image: url("./assets/images/item-b2c2ed.png"); }
.item-2-2.is-topup-chest-reached,
.item-3-2.is-topup-chest-reached,
.item-4-2.is-topup-chest-reached,
.img-2-2.is-topup-chest-reached,
.item-5-2.is-topup-chest-reached,
.img-3-3.is-topup-chest-reached,
.item-13.is-topup-chest-reached {
  filter: drop-shadow(0 0 6px rgba(255, 220, 90, 0.95)) brightness(1.12) saturate(1.2);
}
.text-row {
  z-index: 2;
  display: flex;
  flex-direction: row;
  align-items: center;
  width: 320px;
  height: 28px;
  margin-top: 24px;
  flex-shrink: 0;
}
.text {
  width: auto;
  min-width: 180px;
  height: 18px;
  margin-top: 0;
  color: rgba(253, 255, 187, 1);
  font-family: "Arial Black", Arial, Helvetica, sans-serif;
  font-size: 16px;
  font-weight: 900;
  line-height: 1;
  text-align: left;
  text-transform: uppercase;
  white-space: nowrap;
}
.img-3 {
  width: 20px;
  height: 26px;
  margin-left: 12px;
  background: url("./assets/images/img-6fb773.png") no-repeat center / contain;
  flex-shrink: 0;
}
.text-2 {
  width: auto;
  min-width: 48px;
  height: 18px;
  margin-top: 0;
  margin-left: 10px;
  color: rgba(255, 255, 227, 1);
  font-family: "Arial Black", Arial, Helvetica, sans-serif;
  font-size: 16px;
  font-weight: 900;
  line-height: 1;
  text-align: left;
  white-space: nowrap;
}
.progress-bg-5 { position: absolute; left: 14px; top: 40px; z-index: 171; width: 650px; height: 29px; }
.bg-section-3 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 168;
  display: flex;
  flex-direction: row;
  width: 648px;
  height: 27px;
}
.triangle-4 { width: 13px; height: 25px; background: url("./assets/images/triangle-d70987.png") no-repeat; }
.rect-13 { width: 625px; height: 25px; margin-left: -3px; background: url("./assets/images/rect-c6bfa9.png") no-repeat; }
.triangle-2-3 { width: 14px; height: 25px; margin-left: -3px; background: url("./assets/images/triangle-df6ae7.png") no-repeat; }
.rect-14 {
  position: absolute;
  left: 11px;
  top: 2px;
  z-index: 169;
  width: 624px;
  height: 21px;
  background: url("./assets/images/rect-184672.png") no-repeat;
}
.rect-2-6 {
  position: absolute;
  left: 15px;
  top: 6px;
  z-index: 170;
  width: 0;
  min-width: 0;
  max-width: 611px;
  height: 13px;
  background: url("./assets/images/rect-047534.png") no-repeat;
  background-size: 100% 100%;
  transition: width 0.35s ease;
}
.click-to-visit-the-o {
  width: 620px;
  height: 22px;
  margin-top: 18px;
  margin-left: 37px;
  color: rgba(253, 255, 187, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 16px;
  font-weight: 400;
  line-height: 22px;
  text-align: center;
  text-transform: uppercase;
  text-decoration: underline;
  white-space: nowrap;
}
.click-to-visit-the-o span {
  text-decoration: underline;
}
.rules-3 {
  position: relative;
  z-index: 163;
  width: 685px;
  height: 84px;
  margin-top: 41px;
  margin-left: 3px;
  flex-shrink: 0;
}
.rules-4 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 161;
  width: 683px;
  height: 82px;
  background: url("./assets/images/rules-ca174e.png") no-repeat;
}
.reward-6 {
  position: absolute;
  left: 105px;
  top: 22px;
  z-index: 162;
  width: 475px;
  height: 39px;
  background: url("./assets/images/reward-7dac76.png") no-repeat;
}
.huawenfen { position: absolute; left: 0px; top: 851px; z-index: 224; width: 750px; height: 137px; }
.huawenfen-icon {
  position: absolute;
  left: 0px;
  top: 59px;
  z-index: 218;
  width: 750px;
  height: 39px;
  background: url("./assets/images/huawenfen-044486.png") no-repeat;
}
.shape {
  position: absolute;
  left: 279px;
  top: 65px;
  z-index: 219;
  width: 195px;
  height: 43px;
  background: url("./assets/images/shape-be052d.png") no-repeat;
}
.huawenfen-icon-2 {
  position: absolute;
  left: 199px;
  top: 0px;
  z-index: 220;
  width: 340px;
  height: 136px;
  background: url("./assets/images/img-02ea85.png") no-repeat;
}
.huawenfen-icon-3 {
  position: absolute;
  left: 346px;
  top: 49px;
  z-index: 221;
  width: 73px;
  height: 22px;
  background: url("./assets/images/img-28758f.png") no-repeat;
  opacity: 0.51;
}
.huawenfen-icon-4 {
  position: absolute;
  left: 199px;
  top: 36px;
  z-index: 222;
  width: 340px;
  height: 80px;
  background: url("./assets/images/img-7ef7ff-trim-bd9c44.png") no-repeat;
}
.shape-2 {
  position: absolute;
  left: 310px;
  top: 26px;
  z-index: 223;
  width: 132px;
  height: 111px;
  background: url("./assets/images/shape-a88a81.png") no-repeat;
}
.nav {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 243;
  display: flex;
  flex-direction: column;
  width: 752px;
  height: 189px;
}
.rect-15-stack { position: relative; z-index: 0; width: 750px; height: 92px; flex-shrink: 0; }
.rect-15 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 225;
  width: 750px;
  height: 92px;
  background: url("./assets/images/rect-b168a7.png") no-repeat;
  opacity: 0.8;
}
.logo {
  position: absolute;
  left: 30px;
  top: 9px;
  z-index: 226;
  width: 127px;
  height: 70px;
  background: url("./assets/images/logo-27a255.png") no-repeat;
}
.rect-2-7 {
  position: absolute;
  left: 644px;
  top: 17px;
  z-index: 236;
  width: 82px;
  height: 50px;
  background: url("./assets/images/rect-ff98e3.png") no-repeat;
  pointer-events: none;
}
.nav-menu-hits {
  position: absolute;
  left: 644px;
  top: 17px;
  z-index: 245;
  width: 82px;
  height: 50px;
  pointer-events: none;
}
.nav-menu-hit {
  position: absolute;
  left: 0;
  width: 100%;
  height: 34%;
  padding: 0;
  border: 0;
  background: transparent;
  pointer-events: auto;
  cursor: pointer;
}
.nav-menu-hit--checkin { top: 0; }
.nav-menu-hit--topup { top: 33%; }
.nav-menu-hit--wheel { top: 66%; }
.nav-bg-3 {
  position: absolute;
  left: auto;
  right: 274px;
  top: 20px;
  z-index: 242;
  display: flex;
  flex-direction: row;
  align-items: center;
  width: auto;
  min-width: 140px;
  max-width: 240px;
  height: 48px;
  padding: 0 10px 0 14px;
  box-sizing: border-box;
  overflow: visible;
}
.rounded-3 {
  position: absolute;
  inset: 0;
  z-index: 237;
  width: 100%;
  height: 100%;
  pointer-events: none;
  background: url("./assets/images/rounded-f6b572.png") no-repeat center / 100% 100%;
}
.rect-16 {
  position: absolute;
  left: -7px;
  top: -8px;
  right: -7px;
  bottom: -8px;
  z-index: 238;
  width: auto;
  height: auto;
  pointer-events: none;
  background: url("./assets/images/rect-2b98c2.png") no-repeat center / 100% 100%;
}
.yingyu {
  position: relative;
  left: auto;
  top: auto;
  z-index: 241;
  order: 1;
  flex-shrink: 0;
  width: 22px;
  height: 13px;
  background: url("./assets/images/yingyu-e29e09.png") no-repeat;
}
.english {
  position: relative;
  left: auto;
  top: auto;
  z-index: 239;
  order: 2;
  width: auto;
  min-width: 0;
  height: auto;
  margin-left: 8px;
  margin-right: 6px;
  color: rgba(237, 230, 209, 1);
  font-size: 12.75px;
  line-height: 17px;
  text-align: left;
  white-space: nowrap;
}
.duobianxing {
  position: relative;
  left: auto;
  top: auto;
  z-index: 240;
  order: 3;
  flex-shrink: 0;
  width: 20px;
  height: 18px;
  margin-left: auto;
  background: url("./assets/images/duobianxing-2fe953.png") no-repeat;
}
.nav-bg { position: absolute; left: 497px; top: 22px; z-index: 229; width: 128px; height: 58px; }
.rect-17 {
  position: absolute;
  left: -6px;
  top: -6px;
  z-index: 227;
  width: 126px;
  height: 56px;
  background: url("./assets/images/rect-9ffdb5.png") no-repeat;
}
.login {
  position: absolute;
  left: 0;
  top: -6px;
  z-index: 228;
  width: 100%;
  height: 56px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: rgba(175, 122, 39, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 20px;
  line-height: 1.2;
  text-align: center;
  white-space: nowrap;
  transform: translateY(-2px);
}
.btn-confirm-row {
  z-index: 1;
  display: flex;
  flex-direction: row;
  width: 176px;
  height: 89px;
  margin-top: 12px;
  margin-left: 549px;
  flex-shrink: 0;
}
.btn-confirm { position: relative; z-index: 235; width: 88px; height: 83px; flex-shrink: 0; }
.ellipse-3 {
  position: absolute;
  left: 2px;
  top: 3px;
  z-index: 233;
  width: 77px;
  height: 77px;
  background: url("./assets/images/ellipse-85bb62.png") no-repeat;
}
.btn-confirm-2 {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 234;
  width: 86px;
  height: 81px;
  background: url("./assets/images/btn-confirm-544727.png") no-repeat;
}
.nav-bg-2 {
  position: relative;
  z-index: 232;
  width: 79px;
  height: 79px;
  margin-top: 10px;
  margin-left: 9px;
  flex-shrink: 0;
}
.ellipse-4 {
  position: absolute;
  left: -6px;
  top: -7px;
  z-index: 230;
  width: 77px;
  height: 77px;
  background: url("./assets/images/ellipse-bc3488.png") no-repeat;
}
.discord {
  position: absolute;
  left: 0px;
  top: 0px;
  z-index: 231;
  width: 68px;
  height: 64px;
  background: url("./assets/images/discord-4be2e0.png") no-repeat;
}
.dibu { position: relative; z-index: 253; width: 752px; height: 267px; margin-top: 4818px; flex-shrink: 0; }
.dibu-icon {
  position: absolute;
  left: 0px;
  top: 127px;
  z-index: 244;
  width: 750px;
  height: 138px;
  background: url("./assets/images/dibu-fcc5f4.png") no-repeat;
}
.dibu-icon-2 {
  position: absolute;
  left: 9px;
  top: 81px;
  z-index: 245;
  width: 69px;
  height: 95px;
  background: url("./assets/images/shengnvzhen-dac4a0.png") no-repeat;
}
.dibu-icon-3 {
  position: absolute;
  left: 108px;
  top: 71px;
  z-index: 246;
  width: 63px;
  height: 88px;
  background: url("./assets/images/ajimi-5ac10f.png") no-repeat;
}
.dibu-icon-4 {
  position: absolute;
  left: 191px;
  top: 66px;
  z-index: 247;
  width: 66px;
  height: 76px;
  background: url("./assets/images/makebo-ee961b.png") no-repeat;
}
.dibu-icon-5 {
  position: absolute;
  left: 292px;
  top: 53px;
  z-index: 248;
  width: 71px;
  height: 84px;
  background: url("./assets/images/hema-b0a1ee.png") no-repeat;
}
.dibu-icon-6 {
  position: absolute;
  left: 386px;
  top: 57px;
  z-index: 249;
  width: 48px;
  height: 80px;
  background: url("./assets/images/diduo-6a5202.png") no-repeat;
}
.dibu-icon-7 {
  position: absolute;
  left: 466px;
  top: 66px;
  z-index: 250;
  width: 56px;
  height: 73px;
  background: url("./assets/images/yadang-1d627b.png") no-repeat;
}
.dibu-icon-8 {
  position: absolute;
  left: 533px;
  top: 0px;
  z-index: 251;
  width: 209px;
  height: 228px;
  background: url("./assets/images/hg-event-07-e1a5d7.png") no-repeat;
}
.limited-2 {
  position: absolute;
  left: 233px;
  top: 189px;
  z-index: 252;
  width: 286px;
  height: 32px;
  color: rgba(239, 207, 173, 1);
  font-size: 12.82px;
  line-height: 16px;
  text-align: center;
}

.check {
  opacity: 0;
}
.checkin-days-overlay {
  position: absolute;
  left: 61px;
  top: 42px;
  z-index: 60;
  width: 319px;
  height: 22px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: rgba(255, 248, 230, 1);
  font-family: Arial, Helvetica, sans-serif;
  font-size: 18px;
  font-weight: 700;
  line-height: 22px;
  text-align: center;
  pointer-events: none;
  white-space: nowrap;
}
.checkin-days-count {
  margin: 0 4px;
  color: #ffe27a;
  font-weight: 700;
  text-decoration: underline;
  text-underline-offset: 2px;
}
.day1-text,
.day2-text-2,
.day3-text-2,
.day4-text-2,
.day5-text-2,
.day6-text-2,
.day7-text,
.day8-text-2,
.day9-text-2,
.day10-text {
  color: rgba(229, 181, 13, 1);
  font-size: 16px;
  font-weight: 700;
  line-height: 18px;
  height: 18px;
  text-transform: uppercase;
  white-space: nowrap;
}
.day2-text-2,
.day3-text-2,
.day4-text-2,
.day5-text-2,
.day6-text-2,
.day7-text,
.day8-text-2,
.day9-text-2,
.day10-text {
  z-index: 210;
}
.day10-text {
  left: 14px;
  width: 80px;
}
.day2-text,
.day3-text,
.day4-text,
.day5-text,
.day6-text,
.gem-2,
.day8-text,
.day9-text,
.gem-3 {
  z-index: 210;
  color: rgba(255, 248, 220, 1);
  font-size: 12px;
  font-weight: 700;
  line-height: 14px;
  height: auto;
  white-space: nowrap;
}

.day2.is-checkin-claimed::before,
.day3.is-checkin-claimed::before,
.day4.is-checkin-claimed::before,
.day5.is-checkin-claimed::before,
.day6.is-checkin-claimed::before,
.day7.is-checkin-claimed::before,
.day8.is-checkin-claimed::before,
.day9.is-checkin-claimed::before,
.day10.is-checkin-claimed::before {
  content: '';
  position: absolute;
  left: -5px;
  top: -5px;
  z-index: 200;
  width: 116px;
  height: 161px;
  background: rgba(62, 42, 8, 0.46);
  border-radius: 14px;
  pointer-events: none;
}
.yingwen-stack.is-checkin-claimed::after,
.day2.is-checkin-claimed::after,
.day3.is-checkin-claimed::after,
.day4.is-checkin-claimed::after,
.day5.is-checkin-claimed::after,
.day6.is-checkin-claimed::after,
.day7.is-checkin-claimed::after,
.day8.is-checkin-claimed::after,
.day9.is-checkin-claimed::after,
.day10.is-checkin-claimed::after {
  content: '';
  position: absolute;
  left: 50%;
  top: 42%;
  z-index: 220;
  width: 72px;
  height: 54px;
  transform: translate(-50%, -50%);
  background: url("./assets/images/duihao-decdd6.png") no-repeat center / contain;
  pointer-events: none;
}
.is-checkin-locked {
  filter: grayscale(0.35);
  opacity: 0.72;
}
.is-checkin-claimable {
  filter: brightness(1.08) saturate(1.15);
}
.is-checkin-claimable.is-clickable,
.is-checkin-claimable.is-clickable .layer {
  cursor: pointer;
}
.is-checkin-claimable .day2-bg,
.is-checkin-claimable .day3-bg,
.is-checkin-claimable .day4-bg,
.is-checkin-claimable .day5-bg,
.is-checkin-claimable .day6-bg,
.is-checkin-claimable .day7-bg,
.is-checkin-claimable .day8-bg,
.is-checkin-claimable .day9-bg,
.is-checkin-claimable .day10-bg,
.is-checkin-claimable .yingwen {
  box-shadow: 0 0 0 2px rgba(255, 196, 60, 0.95), 0 0 12px rgba(255, 196, 60, 0.55);
}
.progress-bg-4.is-checkin-disabled {
  opacity: 0.7;
}
.rating.is-milestone-claimable,
.rating-2.is-milestone-claimable,
.reward-3.is-milestone-claimable,
.reward-2-2.is-milestone-claimable {
  filter: drop-shadow(0 0 6px rgba(255, 210, 80, 0.85));
}
.rating.is-milestone-claimed,
.rating-2.is-milestone-claimed,
.reward-3.is-milestone-claimed,
.reward-2-2.is-milestone-claimed {
  filter: saturate(0.45) grayscale(0.2);
}
.rating.is-milestone-locked,
.rating-2.is-milestone-locked {
  filter: grayscale(0.45);
  opacity: 0.7;
}

.reward-5-stack.is-topup-claimable,
.reward-2-3-stack.is-topup-claimable,
.prize-3.is-topup-claimable,
.prize-4.is-topup-claimable,
.prize-5.is-topup-claimable,
.prize-6.is-topup-claimable {
  filter: drop-shadow(0 0 6px rgba(255, 210, 80, 0.85));
}
.reward-5-stack.is-topup-locked,
.reward-2-3-stack.is-topup-locked,
.prize-3.is-topup-locked,
.prize-4.is-topup-locked,
.prize-5.is-topup-locked,
.prize-6.is-topup-locked {
  cursor: default;
}
.reward-5-stack.is-topup-claimed .prize-2,
.reward-2-3-stack.is-topup-claimed .prize-2-2 {
  filter: saturate(0.42) grayscale(0.25);
}
.reward-5-stack.is-topup-claimed::after,
.reward-2-3-stack.is-topup-claimed::after,
.prize-3.is-topup-claimed::after,
.prize-4.is-topup-claimed::after,
.prize-5.is-topup-claimed::after,
.prize-6.is-topup-claimed::after {
  content: '';
  position: absolute;
  left: 50%;
  top: 40%;
  z-index: 220;
  width: 64px;
  height: 50px;
  transform: translate(-50%, -50%);
  pointer-events: none;
  background: url("./assets/images/duihao-decdd6.png") no-repeat center / contain;
  filter: drop-shadow(0 2px 4px rgba(0, 0, 0, 0.35));
}
.prize-3.is-topup-claimed::before,
.prize-4.is-topup-claimed::before,
.prize-5.is-topup-claimed::before,
.prize-6.is-topup-claimed::before {
  content: '';
  position: absolute;
  left: 0;
  top: 0;
  z-index: 200;
  width: 100%;
  height: 100%;
  pointer-events: none;
  background: rgba(55, 48, 38, 0.42);
}
.wheel-disc-stage.is-wheel-spinning {
  transition: transform 3.2s cubic-bezier(0.15, 0.85, 0.2, 1);
}
.is-wheel-disabled {
  pointer-events: none;
  opacity: 0.65;
}
</style>
